version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'server'
    restart: unless-stopped
    depends_on:
      - mongo
    env_file: .env.production
    ports:
      - "3333:3333"
    networks:
      - pokenetwork

  mongo:
    image: mongo:latest
    container_name: 'database'
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pokenetwork

volumes:
  mongodb_data:

networks:
  pokenetwork:
    driver: bridge
